%YAML 1.2
---
# trained model
h5_fname: /home/cory/yolo2-pytorch/data/darknet19.weights.npz

# Udacity crowdai
label_names: [Car, Truck,Pedestrian]
num_classes: 3

# YOLO priors
anchors: [[1.08, 1.19], [3.42, 4.41], [6.63, 11.38], [9.42, 5.11], [16.62, 10.52]]
num_anchors: 5
