%YAML 1.2
---
exp_name: detrac_flow_center_w01
dataset_name: detrac
pretrained_model: /media/cory/data2/yolo2_models/detrac_baseline/detrac_baseline_20.h5
train_output_dir: /home/cory/project/yolo2-pytorch/models/training/detrac_flow_center_w01
network_size_rand_period: 10
inp_size: [960, 512]
out_size: [30, 16] # inp_size / 32
inp_size_candidates: [[960, 512]]
optimizer: SGD  # 'SGD, Adam'
opt_param: all  # 'all, conv345'

start_step: 0
lr_epoch: [0]
lr_val: [!!float 1e-5]
max_epoch: 100

# SGD only
weight_decay: 0.0005
momentum: 0.9

# for training yolo2
object_scale: 5.
noobject_scale: 1.
class_scale: 1.
coord_scale: 1.
iou_thresh: 0.6

# dataset
train_images: /home/cory/project/yolo2-pytorch/flow/detrac_w01_images.txt
train_labels: /home/cory/project/yolo2-pytorch/flow/detrac_w01_labels.txt
val_images: /home/cory/project/yolo2-pytorch/train_data/detrac/detrac_val_images.txt
val_labels: /home/cory/project/yolo2-pytorch/train_data/detrac/detrac_val_labels.txt
batch_size: 1
train_batch_size: 16
val_batch_size: 8

# log & display
disp_interval: 10
